# This is a basic workflow to help you get started with Actions

name: Travis CI
#run: echo "Running jobs Install, Build & Test against $(node -v) ..."
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request: null

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build:
    runs-on: linux
    strategy:
            matrix:
                node_js: ['12']
    steps:
      - uses: actions/checkout@v2
      - run: echo "Installing needed modules"
      - run: npm install
      - run: echo "Running build script ..."
      - run: npm run build
