
name: Travis CI
on:
    pull_request: null
    push:
        branches:
            - master
jobs:
  Build:
    runs-on: Linux
    name: "Build"
    steps:
          - uses: actions/checkout@v2
          - run: npm install
          - run: npm run build
